[workspace]
resolver = "2"
members = ["crates/app", "crates/core", "crates/network"]

[workspace.dependencies]
serde = { version = "1.0.221", features = ["derive"] }
serde_json = "1.0.144"
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
