[workspace]
resolver = "2"
members = ["crates/app", "crates/core", "crates/interface", "crates/network"]

[workspace.dependencies]
serde = { version = "1.0.222", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
