[package]
name = "game_contract"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.38", features = ["rand"] }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
